version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: docker/apache.dockerfile
      args:
        FILES_UID: ${FILES_UID}
        FILES_GID: ${FILES_GID}
    environment:
      - APP_MODE=dev
    ports:
      - "${HOST_APACHE_PORT:-5000}:80"
    container_name: shop
    volumes:
      - ./:/var/www/html/
      - ./docker/apache2.host.conf:/etc/apache2/sites-enabled/local.conf